 version: '3'

 services:
   rabbitmq:
     image: 'rabbitmq:3-management'
     container_name: rabbitmq-server
     environment:
       RABBITMQ_DEFAULT_USER: 'guest'
       RABBITMQ_DEFAULT_PASS: 'guest'
     ports:
      - '15672:15672'
      - '5672:5672'
     restart: always
     networks: 
      - bankly
  
   api:
     container_name: bankly_api
     build:
       context: .
       dockerfile: .\src\TestBankly.Api\Dockerfile
     environment: 
       port: 80
     ports:
       - '80:80'
     depends_on: 
       - rabbitmq
     links: 
       - rabbitmq
     expose:
       - 5011
     networks:
       - bankly
     restart: always

   api_accounts:
     container_name: bankly_accounts
     image: baldini/testacesso
     environment: 
       port: 80
     ports:
       - '80:80'
     expose:
       - 5000
     networks:
       - bankly
   
   elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=jojrn2iMk8nh+WbapCCb
    networks:
      - bankly
   
   kibana:
     container_name: kibana
     image: docker.elastic.co/kibana/kibana:8.8.2
     ports:
       - 5601:5601
     depends_on:
       - elasticsearch
     environment:
       - ELASTICSEARCH_URL=http://localhost:9200
       - ELASTICSEARCH_USERNAME=elastic
       - ELASTICSEARCH_PASSWORD=jojrn2iMk8nh+WbapCCb
     networks:
       - bankly
     
 networks:
   bankly:
     driver: bridge

 volumes:
   elasticsearch-data: